# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
---
version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
